<h1>How to Import numpy Array</h1>

In [2]:
import numpy as np 

In [3]:
a='hello world'

In [4]:
print(a)

hello world


<h4> create an array in numpy</h4>

In [7]:
np.array

<function numpy.core.multiarray.array>

In [8]:
a = np.array([1,2,3]) 

<h4>print array

In [9]:
print(a)

[1 2 3]


<h3> create more then one dimension array</h3>

In [10]:
import numpy as np

In [11]:
a = np.array([[1, 2], [3, 4]]) 

In [12]:
print(a)

[[1 2]
 [3 4]]


<h4>minimum dimensions </h4>

In [14]:
import numpy as np 

In [15]:
a = np.array([1, 2, 3,4,5], ndmin = 2) 

In [16]:
print(a)

[[1 2 3 4 5]]


<h5> specify data type </h5>

In [24]:
a=np.array([1,2,3] ,dtype = np.complex_)

In [25]:
print(a)

[ 1.+0.j  2.+0.j  3.+0.j]


In [27]:
import numpy as np 
dt = np.dtype(np.int32) 
print(dt)

int32


In [29]:
print(np.dtype)


<class 'numpy.dtype'>


In [30]:
help(np.dtype)

Help on class dtype in module numpy:

class dtype(builtins.object)
 |  dtype(obj, align=False, copy=False)
 |  
 |  Create a data type object.
 |  
 |  A numpy array is homogeneous, and contains elements described by a
 |  dtype object. A dtype object can be constructed from different
 |  combinations of fundamental numeric types.
 |  
 |  Parameters
 |  ----------
 |  obj
 |      Object to be converted to a data type object.
 |  align : bool, optional
 |      Add padding to the fields to match what a C compiler would output
 |      for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
 |      or a comma-separated string. If a struct dtype is being created,
 |      this also sets a sticky alignment flag ``isalignedstruct``.
 |  copy : bool, optional
 |      Make a new copy of the data-type object. If ``False``, the result
 |      may just be a reference to a built-in data-type object.
 |  
 |  See also
 |  --------
 |  result_type
 |  
 |  Examples
 |  --------
 |  Usin

<h2>using array-scalar type </h2>

In [33]:
import numpy as np 
dt = np.dtype(np.int32) 
print(dt)

int32


<h3>int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc</h3>

In [35]:
import numpy as np 
dt = np.dtype('i1') 
print(dt)


int8


### we can also use endian notation

In [36]:
dt = np.dtype('>i4') 

In [37]:
print(dt)

>i4


#### The following examples show the use of structured data type

In [41]:
# first create structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print(dt)



[('age', 'i1')]


### apply it to ndarray object 

In [44]:
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)

[(10,) (20,) (30,)]


##### The following examples define a structured data type called 
##### student with a
##### string field 'name'
##### integer field age'
##### float field 'marks'


In [46]:
import numpy as np 
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [47]:
students = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 

In [48]:
print(students)

[(b'abc', 21, 50.0) (b'xyz', 18, 75.0)]


#### get the shape of the array

In [51]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)

(2, 3)


#### resize an array

In [53]:
a = np.array([[1,2,3],[4,5,6]]) 
a.shape=(3,2)

In [54]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [55]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

#### resize an array with reshape funtion

In [56]:
a = np.array([[1,2,3],[4,5,6]]) 

In [57]:
b = a.reshape(3,2) 

In [58]:
print(b)

[[1 2]
 [3 4]
 [5 6]]


#### array range function and  print array

In [59]:
a = np.arange(24) 
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [60]:
a = np.arange(24) 
print(a.ndim)

1


In [61]:
b = a.reshape(2,4,3) 
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


#### observe array b is having three dimensions

#### itemsize to print the length of each element in array

In [63]:
x = np.array([1,2,3,4,5], dtype = np.int8) 
print(x.itemsize)

1


In [65]:
x = np.array([1,2,3,4,5], dtype = np.complex_) 
print(x.itemsize)

16


In [70]:
import numpy as np 
x = np.array([1,2,3,4,5]) 
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


#### create an uninitialized array of specified shape and dtype.

In [74]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print(x)

[[0 0]
 [0 0]
 [0 0]]


#### array of five zeros. Default dtype is float 

In [76]:
import numpy as np 
x = np.zeros(5) 
print(x)

[ 0.  0.  0.  0.  0.]


In [77]:
x = np.zeros((5,), dtype = np.int) 
print(x)

[0 0 0 0 0]


#### Create a new array of specified size and type, filled with ones.

In [79]:
x = np.ones(5) 
print(x)

[ 1.  1.  1.  1.  1.]


In [80]:
x = np.ones([2,2], dtype = int) 
print(x)

[[1 1]
 [1 1]]


## Create an array from existing data

### convert a list to array

In [81]:
x = [1,2,3] 
a = np.asarray(x) 
print(a)

[1 2 3]


In [83]:
x = [1,2,3]
a = np.asarray(x, dtype = float) 
print(a)

[ 1.  2.  3.]


### print type of a 

In [85]:
type(a)

numpy.ndarray

### create an array from tuple

In [87]:
x = (1,2,3) 
a = np.asarray(x) 
print(a)

[1 2 3]


In [88]:
print(type(a))

<class 'numpy.ndarray'>


#### create ndarray from list of tuples 

In [91]:
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print(a)

[(1, 2, 3) (4, 5)]


#### Create array from buffer

In [105]:
import numpy as np 
s = 'Hello World' 
a = np.frombuffer(s, dtype = 'S1')


AttributeError: 'str' object has no attribute '__buffer__'

<b> <font color='red'> not sure why the above function is not working need to investigate. to cross verify</font></b>

#### create list object using range function 

In [108]:
import numpy as np 
list = range(5) 
print(list)

range(0, 5)


#### Obtain Iterator Object From List 

In [109]:
list = range(5) 
it = iter(list)  

# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print(x)

[ 0.  1.  2.  3.  4.]


#### create an array from numerical ranges

In [111]:
x = np.arange(5) 
print(x)

[0 1 2 3 4]


In [112]:
# dtype set 
x = np.arange(5, dtype = float)
print(x)

[ 0.  1.  2.  3.  4.]


In [113]:
# start and stop parameters set 
import numpy as np 
x = np.arange(10,20,2) 
print(x)

[10 12 14 16 18]
